const actionsTypes={
    CHANGE_SEARCHBOX:"CHANGE_SEARCHBOX",
    DARKMODE_EVENT:"DARKMODE_EVENT",
    CHANGE_LIST:'CHANGE_LIST',
    CLICK_BACK:'CLICK_BACK',
    FETCH_COUNTRIES:'FETCH_COUNTRIES',
    FETCH_COUNTRY:'FETCH_COUNTRY',
    FETCH_BORDERS:'FETCH_BORDERS',
}
export default actionsTypes;
